name: Hello World Workflow

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      source_branch:
        description: 'Source branch name'
        required: true
        default: 'main'
      sha:
        description: 'SHA of the commit'
        required: true

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Say Hello
        run: echo "Hello, World! :rocket:" >> $GITHUB_STEP_SUMMARY
