name: Hello World Workflow

on:
  push:
    branches:
      # - main  # Trigger the workflow on pushes to the main branch

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Say Hello
        run: echo "Hello, World! :rocket:" >> $GITHUB_STEP_SUMMARY
