name: Hello World Workflow

on:
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Say Hello
        run: echo "Hello, World! :rocket:" >> $GITHUB_STEP_SUMMARY
