name: Hello My Name Workflow

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch

jobs:
  hello_world_job:
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello
        run: echo "Hello, my name is Syazmi"
