name: Run Other Workflows

on:
  workflow_dispatch:

jobs:
  run_workflows:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run First Workflow
        uses: ./.github/workflows/print_hello.yaml
      - name: Run Second Workflow
        uses: ./.github/workflows/print_name.yaml
