name: Run Workflows

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      source_branch:
        description: 'Source branch name'
        required: true
        default: 'main'
      sha:
        description: 'SHA of the commit'
        required: true

jobs:
  trigger_workflow:
    name: Run First Workflow
    uses: ./.github/workflows/print_hello.yaml
